version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/Toronto
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: prettier
    versions:
    - "> 1.19.1"
  - dependency-name: react-datepicker
    versions:
    - "> 1.4.1"
  - dependency-name: react-responsive-select
    versions:
    - "> 3.1.4"
  - dependency-name: gatsby-image
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: react-leaflet
    versions:
    - 3.0.5
    - 3.1.0
